out_dir: models
dataset: data/big/mcrae-wordnet-vgg16.32bit
number_of_episodes: 30000
batch_size: 30
number_of_images: 2
embedding_size: 50
vocabulary_size: 100
temperature: 20
optimizer: adam
analysis_window: 30
sender_type: agnostic
memory_sampling_mode: last
algorithm: reinforce
#algorithm: qlearning
